version: '3.4'

networks:
  proxy:
    external: true
  internal:
    external: 
      name: demandjs.localhost



services:
  docs-web:
    build:
      context: .
      args:
        BUILD_ENV: "development"
    command: [sh, -c, "yarn start"]
    env_file:   
    - ./.env
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.demandjs-docs.rule=Host(`docs.demandcluster.com`)"
      - "traefik.http.routers.demandjs-docs.tls=true"
      - "traefik.http.routers.demandjs-docs.entrypoints=websecure"
      - "traefik.http.routers.demandjs-docs.service=docs-service"
      - "traefik.http.services.docs-service.loadbalancer.server.port=4242"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - internal
    environment:
      REACTION_APP_NAME: "demand-docs.web"
    ports:
      - 4242:4242
      - 35729:35729
    volumes:
      - $HOME/.cache/yarn-offline-mirror:/home/node/.cache/yarn-offline-mirror
      - web-yarn:/home/node/.cache/yarn
      - .:/usr/local/src/demand-app # link everything from the root folder on the host machine into the container
      - empty_node_modules:/usr/local/src/demand-app/node_modules # except do not link the host node_modules in because it will override the container node_modules
      - node_modules:/usr/local/src/node_modules # persist the node_modules that is used, which is up one folder level in the container

volumes:
  web-yarn:
  empty_node_modules:
  node_modules:
